### ISSUE TITLE
TypeError: Argument 'by' has incorrect type (expected bytes, got str)

### ISSUE THREAD

**Issue by XavierCLL** [sobotklp/pycksum#2]
Hi, I get the following error with the basic test, using:
Pycksum 0.4.1, Python 3.5.1 and Archlinux

```
In [15]: import pycksum
In [16]: ck = pycksum.cksum("Any string")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-16-35c7dc399fac> in <module>()
----> 1 ck = pycksum.cksum("Any string")

/usr/lib/python3.5/site-packages/pycksum/__init__.py in cksum(o)
    114 def cksum(o):
    115     c = Cksum()
--> 116     c.add(o)
    117     return c.get_cksum()

/usr/lib/python3.5/site-packages/pycksum/__init__.py in add(self, obj)
     93         if hasattr(obj, '__iter__'):
     94             for b in iter(obj):
---> 95                 self._add(b)
     96         else:
     97             self._add(obj)

/usr/lib/python3.5/site-packages/pycksum/__init__.py in _add(self, b)
     87
     88     def _add(self, b):
---> 89         self._ck, incsz = _memcksum(b, self._ck)
     90         self._sz += incsz
     91

_pycksum.pyx in _pycksum._memcksum (ext/_pycksum.c:515)()

TypeError: Argument 'by' has incorrect type (expected bytes, got str)
```

**Comment by LuxoftAKutsan** [comment]
I have the same issue, is it going to be fixed?

**Comment by sobotklp** [comment]
Can you please describe the OS, Python version, version of CPython that you're using? I wasn't able to reproduce this issue, but I'll try again.

**Comment by johnnybubonic** [comment]
hey, getting this too (i know, sorry, necrobumping)

Arch is now at 3.7 but still occurring.

[Arch](https://www.archlinux.org/) is a rolling linux distro so it doesn't have a version number, but i'm on a fully updated system as of the time of writing this comment.

using pycksum directly from pypi.

```
>>> pycksum.__version__
'0.4.2'
>>> sys.version
'3.7.0 (default, Jul 15 2018, 10:44:58) \n[GCC 8.1.1 20180531]'
```

test case:

```
[root@archtest tmp]# echo 'this is a test' > testfile
[root@archtest tmp]# cksum testfile 
4273069754 15 testfile
[root@archtest tmp]# python -q
>>> import pycksum
>>> c = pycksum.Cksum()
>>> with open('/tmp/testfile', 'rb') as f:
...     d = f.read()
... 
>>> for b in d:
...     c.add(b)
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/root/.local/lib/python3.7/site-packages/pycksum/__init__.py", line 97, in add
    self._add(obj)
  File "/root/.local/lib/python3.7/site-packages/pycksum/__init__.py", line 89, in _add
    self._ck, incsz = _memcksum(b, self._ck)
  File "_pycksum.pyx", line 9, in _pycksum._memcksum (ext/_pycksum.c:515)
TypeError: Argument 'by' has incorrect type (expected bytes, got int)

```

BUT opening the file itself works:

```
>>> pycksum.cksum(open('/tmp/testfile', 'rb'))
4273069754

```

using a file handler opened externally works (as expected, since the above works):

```
>>> with open('/tmp/testfile', 'rb') as f:
...     c.add(f)
... 
>>> c.get_cksum()
4273069754

```

but not iteration on the handler, either:

```
>>> c = pycksum.Cksum()
>>> with open('/tmp/testfile', 'rb') as f:
...     for b in f:
...             c.add(b)
... 
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/root/.local/lib/python3.7/site-packages/pycksum/__init__.py", line 95, in add
    self._add(b)
  File "/root/.local/lib/python3.7/site-packages/pycksum/__init__.py", line 89, in _add
    self._ck, incsz = _memcksum(b, self._ck)
  File "_pycksum.pyx", line 9, in _pycksum._memcksum (ext/_pycksum.c:515)
TypeError: Argument 'by' has incorrect type (expected bytes, got int)

```

hope this helps.

EDIT:

sorry, also - can confirm OP's issue, both when passing a string or a bytestring:

```
>>> ck = pycksum.cksum("Any string")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.local/lib/python3.7/site-packages/pycksum/__init__.py", line 116, in cksum
    c.add(o)
  File "/root/.local/lib/python3.7/site-packages/pycksum/__init__.py", line 95, in add
    self._add(b)
  File "/root/.local/lib/python3.7/site-packages/pycksum/__init__.py", line 89, in _add
    self._ck, incsz = _memcksum(b, self._ck)
  File "_pycksum.pyx", line 9, in _pycksum._memcksum (ext/_pycksum.c:515)
TypeError: Argument 'by' has incorrect type (expected bytes, got str)
>>> ck = pycksum.cksum(b"Any string")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.local/lib/python3.7/site-packages/pycksum/__init__.py", line 116, in cksum
    c.add(o)
  File "/root/.local/lib/python3.7/site-packages/pycksum/__init__.py", line 95, in add
    self._add(b)
  File "/root/.local/lib/python3.7/site-packages/pycksum/__init__.py", line 89, in _add
    self._ck, incsz = _memcksum(b, self._ck)
  File "_pycksum.pyx", line 9, in _pycksum._memcksum (ext/_pycksum.c:515)
TypeError: Argument 'by' has incorrect type (expected bytes, got int)

```

**Comment by erictrudeau** [comment]
I just ran into this issue as well and found a workaround.  If you use c._add(b) instead of c.add(b), that will get past the problematic code (note the underscore).

Also, be sure to open the file in **rb** mode (read binary).

```
c = pycksum.Cksum()
with open('/tmp/testfile', 'rb') as f:
    for b in f:
        c._add(b)
```

The problem is in this code from [pycksum/__init__.py](https://github.com/sobotklp/pycksum/blob/master/pycksum/__init__.py).  When chunking a file, the chunk will technically have an iterator, but not in a way that works.  I'm not quite sure how to fix it though.

```
    def add(self, obj):
        if hasattr(obj, '__iter__'):
            for b in iter(obj):
                self._add(b)
        else:
            self._add(obj)
```

Hopefully this helps someone else that runs into the same issue.

**Comment by sobotklp** [comment]
This is (finally) fixed with pycksum==0.4.7

**Comment by enkiusz** [comment]
This is still an issue. Running on pycksum 0.4.7 in a venv with python 3.10 on ubuntu 22.04.5. Reproduction steps:

```
✗ docker run -it ubuntu:22.04  
root@23a0ae90b64b:/# apt update --quiet
root@23a0ae90b64b:/# apt install python3-venv build-essential libpython3-dev
[...]
root@23a0ae90b64b:/# mkdir venv  
root@23a0ae90b64b:/# python3 -m venv venv
root@23a0ae90b64b:/# source venv/bin/activate
(venv) root@23a0ae90b64b:/# echo test > test.txt
(venv) root@23a0ae90b64b:/# python3
Python 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycksum, sys
>>> from pathlib import Path
>>> sys.version
'3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]'
>>> pycksum.__version__
'0.4.7'
>>> p = Path('test.txt')
>>> bt = p.read_bytes()
>>> bt
b'test\n'
>>> c = pycksum.Cksum()
>>> c.add(bt)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/venv/lib/python3.10/site-packages/pycksum/__init__.py", line 303, in add
    self._add(b)
  File "/venv/lib/python3.10/site-packages/pycksum/__init__.py", line 297, in _add
    self._ck, incsz = _memcksum(b, self._ck)
TypeError: Argument 'by' has incorrect type (expected bytes, got int)
>>> c._add(bt)
>>> c.get_cksum()
935282863
>>> 
(venv) root@23a0ae90b64b:/# deactivate 
root@23a0ae90b64b:/# 
exit
```
